### ISSUE TITLE
add support for 4mC motif detection

### ISSUE THREAD

**Issue by winterlich** [MicrobialDarkMatter/nanomotif#20]
Great tool!
Would it be possible to integrate motif detection for 4mC and potentially other or even user defined modifications?

**Comment by SorenHeidelbach** [comment]
Thank you!
Currently we do not support it. But it will be integrated soon to support 4mC and any other modification supported by modkit. 

Best

**Comment by ArtRand** [comment]
@SorenHeidelbach 

Modkit does support 4mC actually, but there isn't a single-letter code for it [page 9 of spec](https://samtools.github.io/hts-specs/SAMtags.pdf), so you have to use the ChEBI code `21839` instead of a single letter. But if you have a modBAM with 4mC, `modkit pileup` will work.

**Comment by SorenHeidelbach** [comment]
Thank you @ArtRand !

We have updated motif_discovery to work with 4mC (#26)

The other modules have not been updated yet to support 4mC, but will shortly

Best Søren!
