### ISSUE TITLE
monoculture testrun not working?

### ISSUE THREAD

**Issue by mult1fractal** [MicrobialDarkMatter/nanomotif#32]
Hello Nanomotif-Developers

I wanted to test your tool on a monoculture as described in your readme.
I provided the files as suggested by your guide (bed-file was created with modkit using your command, the config file I created accounting to your [test-data](https://github.com/MicrobialDarkMatter/nanomotif/blob/main/datasets/binnary_testdata/contig_bin.tsv))

If I provide all the needed files I will get the suggestion on how to use nanomotif:

```
nanomotif find_motifs ref-fasta/barcode20.fasta barcode20_pileup.bed contig_bin.tsv -t 10 --out OUT
usage: nanomotif [-h] [--version]
                 {find_motifs,check-installation,detect_contamination,include_contigs,MTase-linker} ...

Motif identification and utilisation commands

positional arguments:
  {find_motifs,check-installation,detect_contamination,include_contigs,MTase-linker}
                        Command descriptions
    find_motifs         Identify methylated motifs on and contig and bin level
    detect_contamination
                        Detect contamination in bins
    include_contigs     Include contigs in bins
    MTase-linker        Commands related to MTase-linker

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
```

pileup.bed: (modkit pileup --only-tabs ${modmapped_bam} ${name}_pileup.bed)

```
head barcode20_pileup.bed  
contig_1        345     346     m       1       +       345     346     255,0,0 1       0.00    0       1       0       000       0
contig_1        348     349     a       1       +       348     349     255,0,0 1       100.00  1       0       0       000       0
contig_1        349     350     a       1       +       349     350     255,0,0 1       100.00  1       0       0       000       0
contig_1        351     352     a       1       +       351     352     255,0,0 1       0.00    0       1       0       000       0
contig_1        352     353     m       1       +       352     353     255,0,0 1       0.00    0       1       0       000       0
contig_1        353     354     m       1       +       353     354     255,0,0 1       100.00  1       0       0       000       0
contig_1        354     355     a       1       +       354     355     255,0,0 1       0.00    0       1       0       000       0
contig_1        357     358     m       1       +       357     358     255,0,0 1       0.00    0       1       0       000       0
contig_1        358     359     m       1       +       358     359     255,0,0 1       0.00    0       1       0       000       0
contig_1        360     361     a       1       +       360     361     255,0,0 1       0.00    0       1       0       000       0
```

cat contig_bin.tsv:

`cat contig_bin.tsv  
>contig_1    bar
>contig_2    bar
>contig_3    bar
>contig_4    bar
>contig_5    bar
>contig_6    bar`

I'm not sure if I'm missing something

Kind regards 
Mike

**Comment by SorenHeidelbach** [comment]
Hmm, can you provide the error message you get when you run the command?

**Comment by mult1fractal** [comment]
this here was the error msg^^ :

````
usage: nanomotif [-h] [--version]
                 {find_motifs,check-installation,detect_contamination,include_contigs,MTase-linker} ...

Motif identification and utilisation commands

positional arguments:
  {find_motifs,check-installation,detect_contamination,include_contigs,MTase-linker}
                        Command descriptions
    find_motifs         Identify methylated motifs on and contig and bin level
    detect_contamination
                        Detect contamination in bins
    include_contigs     Include contigs in bins
    MTase-linker        Commands related to MTase-linker

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
````


I didn't get anything else unfortunately. I copied it directly from the terminal

**Comment by mult1fractal** [comment]
![image](https://github.com/MicrobialDarkMatter/nanomotif/assets/40232542/5d660bff-8c80-4442-b119-db5915821ca7)

**Comment by mult1fractal** [comment]
check_installation command works.. but with --version I get the Help-msg again
I'm using nanomotif in a docker

![image](https://github.com/MicrobialDarkMatter/nanomotif/assets/40232542/197e6b3e-34a2-42e7-b687-a151fb7ec2dc)

**Comment by SorenHeidelbach** [comment]
Could get you to run `nanomotif --version`? I suspect it stems from a faulty version, that have now been deprecated

**Comment by mult1fractal** [comment]
0.3.0

**Comment by SorenHeidelbach** [comment]
Yes, that is the deprecated version, sorry for the incovenience. Yes 0.3.1 is working, the argumentparser might be subject to future reworks, but will come with a version bump 0.3.x -> 0.4.x

**Comment by mult1fractal** [comment]
Thank you
Now I get proper error-msgs that I can work with :)

Btw. I use nanomotif in a docker.
should I provide you the docker receipt so other users have another option for easy installation?

**Comment by SorenHeidelbach** [comment]
That would be nice, thank you!

**Comment by mult1fractal** [comment]
From nanozoo/template:3.8--12e1614

RUN apt-get update && apt install -y libzstd-dev libz-dev gcc procps git gzip tar wget && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN python -m venv nanomotif
RUN . nanomotif/bin/activate # . is eaqual command to "source"
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools wheel
RUN pip install nanomotif
RUN nanomotif check-installation
