### ISSUE TITLE
installation MTase-linker

### ISSUE THREAD

**Issue by MBiggel** [MicrobialDarkMatter/nanomotif#34]
I installed nanomotif via conda as described in the instructions. 

Running 
`nanomotif MTase-linker install`
gives 
`nanomotif: error: argument command: invalid choice: 'MTase-linker' (choose from 'find-motifs', 'score-motifs', 'bin-consensus', 'complete-workflow', 'check-installation')`

Does conda provide the current nanomotif version?

Thanks for fixing this,
Michael

**Comment by JSBoejer** [comment]
Hello Michael,

Thank you for bringing this to our attention. You're correct that conda does not provide the current version of nanomotif (0.3.1), which include the MTase-linker module. We will look into it, and update the conda package ASAP.
