### ISSUE TITLE
Question: Read vs contig level analysis

### ISSUE THREAD

**Issue by nschuiling** [MicrobialDarkMatter/nanomotif#35]
In my analysis I am interested in obtaining (1) methylation motifs, (2) (non)methylated occurrences of those motifs at the read level. The output of nanomotif seems highly relevant for this, but is at the contig rather than read level.

I was therefore wondering whether it would be possible to provide binned reads (instead of contigs) as input: a .fasta reads file and a read-to-bin .tsv. How/Would this affect the results?

**Comment by SorenHeidelbach** [comment]
It is not something that is possible to do with Nanomotif. But, it is something we might look into in the future. To achieve it now, you would have to create a pileup formatted file of the certainty of methylation at each position of the read. 

Best regards Søren
