### ISSUE TITLE
Unclear what input files are needed. - correction of required files commands

### ISSUE THREAD

**Issue by SebastianDall** [MicrobialDarkMatter/nanomotif#4]
Hello Søren and Jacob

I am uncertain of the input files to the tools from the documentation. Is it possible you can give a more detailed documentation.

In the "Required files section":
```
samtools fastq -T MM,ML {DORADO_BASECALLS.sam} > {READS.fastq}
minimap2 -ax map-ont -y {ASSEMBLY.fasta} {READS.fastq} |
        samtools view -bS |
        samtools sort > {ALIGNMENT.bam}
        samtools index {ALIGNMENT.bam}    <----- What is the point of the bam.bai file?
modkit pileup {ALIGNMENT.bam} --only-tabs
```
Also as of modkit pileup 0.2.3 the command line is:

Usage: modkit pileup [OPTIONS] <IN_BAM> <OUT_BED>

change to:

`modkit pileup --only-tabs {ALIGNMENT.bam} {OUT.bed} `

Finally, there needs to be line breaks - the final will look like:

```
samtools fastq -T MM,ML {DORADO_BASECALLS.sam} > {READS.fastq}
minimap2 -ax map-ont -y {ASSEMBLY.fasta} {READS.fastq} | \ <---
        samtools view -bS | \ <--
        samtools sort > {ALIGNMENT.bam}
samtools index {ALIGNMENT.bam}    <----- What is the point of the bam.bai file?
modkit pileup --only-tabs {ALIGNMENT.bam} {OUT.bed}
```

I hope that is correct.

**Comment by SorenHeidelbach** [comment]
That is correct, i have changed to the required files section. Thank you
