### ISSUE TITLE
Suggestion for documentation

### ISSUE THREAD

**Issue by Serka-M** [MicrobialDarkMatter/nanomotif#5]
Thanks for the developing the tool. It installs nicely through pip. Here's a few suggestions for the documentation page that might be useful for new users or users that are not well-experienced in bioinformatics.

* For the Conda installation, consider including CPU-based dependencies needed to prepare the input for nanomotif. They don't clash with nanomotif itself and users are expected to apply them anyways. Example below:

`conda create -n nanomotif -c conda-forge -c bioconda python=3.9 minimap2=2.26 samtools=1.18 ont-modkit=0.2.2`

* For re-mapping the modcalls to reference, all commands can be piped together, which for my sample made the process 25 % faster and saved 800 GB of storage in intermediate files . An example is presented below, which can later be expanded into a small pipeline.

```
REF=/path/to/assembly.fasta       # Reference sequence 
BAM_IN=/path/to/modcalls.bam      # Modification basecalls
BAM_OUT=modcalls_mapped.bam       # Output for re-mapped basecalls
THREADS_MAIN=100                  # Threads usage for main processes 
THREADS_SUB=10                    # Threads usage for minor processes 

samtools fastq --threads ${THREADS_SUB} -T MM,ML ${BAM_IN} | minimap2 -t ${THREADS_MAIN} -ax map-ont -y ${REF} - | samtools view --threads ${THREADS_SUB} -bS | samtools sort --threads $((${THREADS_SUB}/2)) --write-index -o ${BAM_OUT}##idx##${BAM_OUT}.bai
```

* Consider including an example command on how to prepare contig-bin linkage file for the `bin-consensus` step. Shell-based example presented below:
```
BINS=/path/to/bins    # Bin directory
EXT="fa"              # Filename extension
grep ">" ${BINS}/*.${EXT} | sed "s/.*\///" | sed "s/.${EXT}:>/\t/" | awk -F'\t' '{print $2 "\t" $1}' > contig_bin.tsv
```

**Comment by SorenHeidelbach** [comment]
Thank you for the suggestion. The pipe has been added
