### ISSUE TITLE
motif_discovery step fails at end

### ISSUE THREAD

**Issue by osvatic** [MicrobialDarkMatter/nanomotif#59]
I recently ran nanomotif on a large set of genomes. motif_discovery and MTase_linker ran well on most of the genomes but a few have failed at the end of the motif_discovery step.

```
nanomotif motif_discovery genome.fa modcalls_v7/genome.pileup.bed ref/genome.contig_bin.tsv -t 8 --out nanomotif_results/genome_motifs

```

Here is the error file for the full run, which contains the failed motif_discovery run and attempted MTase_linker afterwards:
[nanomotif_2311358.txt](https://github.com/user-attachments/files/16194447/nanomotif_2311358.txt)

Here are all of the logs for motif_discovery:
[find-motifs.1840007.log](https://github.com/user-attachments/files/16194526/find-motifs.1840007.log)
[find-motifs.1840006.log](https://github.com/user-attachments/files/16194521/find-motifs.1840006.log)
[motif_discovery.main.log](https://github.com/user-attachments/files/16194522/motif_discovery.main.log)
[find-motifs.1840012.log](https://github.com/user-attachments/files/16194523/find-motifs.1840012.log)
[find-motifs.1840009.log](https://github.com/user-attachments/files/16194524/find-motifs.1840009.log)
[find-motifs.1840008.log](https://github.com/user-attachments/files/16194525/find-motifs.1840008.log)

It looks like no motifs were found. Would this cause the issue?

**Comment by SorenHeidelbach** [comment]
The error does indeed result from improper handling of no motifs identified. The issue has been fixed in Nanomotif version 0.4.11.
