### ISSUE TITLE
Question: short reads assembly as input

### ISSUE THREAD

**Issue by rzhao-2** [MicrobialDarkMatter/nanomotif#81]
Hi Søren, many thanks for making such a wonderful tool.

In my current analysis, I have a metagenomic sample which has been sequenced for both short and long reads, but the volume of short reads (~85 Gb) greatly outweighs that of the long reads (4 Gb). As hybrid assembly hasn't been very successful so far, is it possible for Nanomotif to use an assembly generated with short reads as input?

**Comment by SorenHeidelbach** [comment]
It is entirely possible. The main concern i the degree of assembly fragmentation, as increased fragmentation leads to fewer motif observations and hence makes motif identification less sensitive. 

Best Søren
